[[main]]
name = "About"
url  = "/about/"
weight = 10

[[main]]
name = "Activities"
url  = "/activities/"
weight = 20

[[main]]
name = "Repeaters"
url  = "/repeaters/"
weight = 30

[[main]]
name = "Nets"
url  = "/nets/"
weight = 40


[[main]]
name = "Downloads"
url  = "/downloads/"
weight = 60

[[main]]
name = "Blog"
url  = "/blog/"
weight = 70

[[main]]
name = "Contact"
url  = "/contact/"
weight = 80

[[main]]
name = "Join"
url  = "/join/"
weight = 90
