name: Nightly Cloudflare Pages rebuild

on:
  schedule:
    # Runs every day at 2:00 AM Eastern Time (≈ 7:00 AM UTC)
    - cron: "0 7 * * *"
  workflow_dispatch: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages deploy hook
        run: curl -fsS -X POST "$CF_PAGES_HOOK"
        env:
          CF_PAGES_HOOK: ${{ secrets.CF_PAGES_HOOK }}
